version: '3.7'
services:
    jenkins_devops:
      build: .
      build:
        context: .
        dockerfile: Dockerfile
      container_name: jenkins_devops
      ports:
        - 80:8080
      mem_limit: 2147483648
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      volumes:
        - jenkins_home:/var/jenkins_home

volumes:
    jenkins_home: