version: '3.7'
services:
    jenkins_devops:
      build: .
      build:
        context: .
        dockerfile: Dockerfile
      container_name: jenkins_devops
      ports:
        - 80:8080
      deploy:
        resources:
          limits:
            memory: 2000M
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
          window: 120s
      volumes:
        - jenkins_home:/var/jenkins_home

volumes:
    jenkins_home:
